#!/bin/bash

# Provider-aware AI coding-agent wrappers for the dev-user container.
#
# The plain wrappers (claudex, codexx, cursorx, opencodex, pix, clinex, grokx)
# run each CLI with its full-permission flag. The `-azure` / `-xai` variants
# point the same CLI at another provider by writing that CLI's own config file
# with an ENV REFERENCE — never a key value — and then launching it.
#
# Every key is read from the environment. Put the names you use in
# docker/local/cli/.env, which is git-ignored; docker/local/cli/.env.example
# lists the names with no values. GLM wrappers are intentionally not provided.

_ai_require() {
    command -v "$1" >/dev/null 2>&1 || { print.error "$1 is not on PATH. Rebuild the container."; return 1; }
}

_ai_require_env() {
    local name="$1"
    [[ -n "${!name:-}" ]] || { print.error "$name is not set. Add it to docker/local/cli/.env."; return 1; }
}

_azure_base_url() {
    if [[ -n "${AZURE_OPENAI_BASE_URL:-}" ]]; then
        printf '%s' "$AZURE_OPENAI_BASE_URL"
    elif [[ -n "${AZURE_OPENAI_RESOURCE:-}" ]]; then
        printf 'https://%s.services.ai.azure.com/openai/v1' "$AZURE_OPENAI_RESOURCE"
    else
        return 1
    fi
}

_provider_env_or_die() {
    case "$1" in
        azure) _ai_require_env AZURE_OPENAI_API_KEY || return 1; _azure_base_url >/dev/null || { print.error "AZURE_OPENAI_RESOURCE or AZURE_OPENAI_BASE_URL is not set."; return 1; } ;;
        xai) _ai_require_env XAI_API_KEY || return 1; [[ -n "${XAI_BASE_URL:-https://api.x.ai/v1}" ]] || { print.error "XAI_BASE_URL is empty."; return 1; } ;;
    esac
}

_codex_provider() {
    local provider="$1" model="$2" base key config_dir profile; shift 2
    [[ "$provider" == azure ]] && key=AZURE_OPENAI_API_KEY || key=XAI_API_KEY
    base="$(_azure_base_url 2>/dev/null || printf '%s' "${XAI_BASE_URL:-https://api.x.ai/v1}")"
    config_dir="${CODEX_HOME:-${HOME}/.codex}"; profile="${config_dir}/${provider}.config.toml"
    mkdir -p "$config_dir"
    python3 - "$profile" "$provider" "$model" "$base" "$key" <<'PY'
from pathlib import Path
import sys
path, provider, model, base, key = sys.argv[1:]
name = "Azure OpenAI / Microsoft Foundry" if provider == "azure" else "xAI Grok"
path = Path(path)
path.write_text(f'''# Generated by docker/ai_wrappers.sh; do not hand-edit.
model = "{model}"
model_provider = "{provider}"
[model_providers.{provider}]
name = "{name}"
base_url = "{base}"
env_key = "{key}"
wire_api = "responses"
''')
PY
    if [[ "$provider" == azure ]]; then export AZURE_OPENAI_API_KEY; else export XAI_API_KEY; fi
    case "${1:-}" in
        -c|--continue) shift; command codex -p "$provider" resume --last --dangerously-bypass-approvals-and-sandbox "$@" ;;
        -l|--last) shift; command codex -p "$provider" resume --last --dangerously-bypass-approvals-and-sandbox "$@" ;;
        -r|--resume) shift; if [[ -n "${1:-}" && "$1" != -* ]]; then local id="$1"; shift; command codex -p "$provider" resume "$id" --dangerously-bypass-approvals-and-sandbox "$@"; else command codex -p "$provider" resume --all --dangerously-bypass-approvals-and-sandbox "$@"; fi ;;
        *) command codex -p "$provider" --dangerously-bypass-approvals-and-sandbox "$@" ;;
    esac
}

function codexx() {
    case "${1:-}" in
        -c|--continue) shift; print.success "Continuing the most recent Codex session with full permissions..."; command codex resume --last --dangerously-bypass-approvals-and-sandbox "$@" ;;
        -l|--last) shift; print.success "Resuming last Codex session with full permissions..."; command codex resume --last --dangerously-bypass-approvals-and-sandbox "$@" ;;
        -r|--resume) shift; if [[ -n "${1:-}" && "$1" != -* ]]; then local id="$1"; shift; command codex resume "$id" --dangerously-bypass-approvals-and-sandbox "$@"; else command codex resume --all --dangerously-bypass-approvals-and-sandbox "$@"; fi ;;
        *) print.success "Starting Codex with full permissions..."; command codex --dangerously-bypass-approvals-and-sandbox "$@" ;;
    esac
}
function codex-azure() { _ai_require codex || return 1; _provider_env_or_die azure || return 1; _codex_provider azure "${AZURE_OPENAI_DEFAULT_MODEL:-${AZURE_OPENAI_MODEL_DAILY:-gpt-5.4-mini-azure}}" "$@"; }
function codex-xai() { _ai_require codex || return 1; _provider_env_or_die xai || return 1; _codex_provider xai "${XAI_DEFAULT_MODEL:-${XAI_MODEL_DAILY:-grok-4.3}}" "$@"; }

function claudex() {
    case "${1:-}" in
        -c|--continue) shift; command claude --continue --dangerously-skip-permissions "$@" ;;
        -r|--resume) shift; if [[ -n "${1:-}" && "$1" != -* ]]; then local id="$1"; shift; command claude --resume "$id" --dangerously-skip-permissions "$@"; else command claude --resume --dangerously-skip-permissions "$@"; fi ;;
        *) print.success "Starting Claude Code with full permissions..."; command claude --dangerously-skip-permissions "$@" ;;
    esac
}

_opencode_sync_provider() {
    local provider="$1" base="$2" key="$3" model="$4" daily="$5" reasoning="$6" config="${OPENCODE_CONFIG:-${HOME}/.config/opencode/opencode.json}"
    mkdir -p "$(dirname "$config")"
    python3 - "$config" "$provider" "$base" "$key" "$model" "$daily" "$reasoning" <<'PY'
import json, sys
from pathlib import Path
path, provider, base, key, model, daily, reasoning = sys.argv[1:]
path = Path(path)
try: data=json.loads(path.read_text()) if path.exists() else {}
except (OSError, json.JSONDecodeError): data={}
data.setdefault("provider", {})
data["provider"][provider]={"options":{"apiKey":f"{{env:{key}}}","baseURL":base},"whitelist":[daily, reasoning],"models":{}}
for mid, label in ((daily,"daily"),(reasoning,"reasoning")):
    data["provider"][provider]["models"][mid]={"id":mid,"name":f"{mid} ({label})","attachment":True,"modalities":{"input":["text","image"],"output":["text"]}}
data["model"]=f"{provider}/{model}"
path.write_text(json.dumps(data, indent=2)+"\n")
PY
}
function opencodex() { _ai_require opencode || return 1; print.success "Starting OpenCode with full permissions (--auto)..."; command opencode --auto "$@"; }
function opencode-xai() { _ai_require opencode || return 1; _provider_env_or_die xai || return 1; local d="${XAI_MODEL_DAILY:-grok-4.3}" r="${XAI_MODEL_REASONING:-grok-4.6}"; _opencode_sync_provider xai "${XAI_BASE_URL:-https://api.x.ai/v1}" 'XAI_API_KEY' "${XAI_DEFAULT_MODEL:-$d}" "$d" "$r"; command opencode --auto "$@"; }
function opencode-azure() { _ai_require opencode || return 1; _provider_env_or_die azure || return 1; local d="${AZURE_OPENAI_MODEL_DAILY:-gpt-5.4-mini-azure}" r="${AZURE_OPENAI_MODEL_REASONING:-gpt-5.4-azure}"; _opencode_sync_provider azure "$(_azure_base_url)" 'AZURE_OPENAI_API_KEY' "${AZURE_OPENAI_DEFAULT_MODEL:-$d}" "$d" "$r"; command opencode --auto "$@"; }

function pix() { _ai_require pi || return 1; print.success "Starting Pi with full permissions (--approve)..."; command pi --approve "$@"; }
_pi_provider() {
    local provider="$1" base="$2" key="$3" model="$4" daily="$5" reasoning="$6"; shift 6
    local file="${PI_MODELS_FILE:-${HOME}/.pi/agent/models.json}"; mkdir -p "$(dirname "$file")"
python3 - "$file" "$provider" "$base" "$key" "$model" "$daily" "$reasoning" <<'PY'
import json,sys
from pathlib import Path
path,provider,base,key,model,daily,reasoning=sys.argv[1:]
path = Path(path)
try: data=json.loads(path.read_text()) if path.exists() else {}
except (OSError,json.JSONDecodeError): data={}
models=[]
for mid,label in ((daily,"daily"),(reasoning,"reasoning")):
    if mid and not any(item["id"] == mid for item in models):
        models.append({"id":mid,"name":f"{mid} ({label})","reasoning":True,"input":["text","image"],"contextWindow":200000,"maxTokens":32768})
data.setdefault("providers",{})[provider]={"baseUrl":base,"api":"openai-completions","apiKey":key,"compat":{"supportsDeveloperRole":False,"supportsReasoningEffort":True},"models":models}
path.write_text(json.dumps(data,indent=2)+"\n")
PY
    command pi --provider "$provider" --model "$model" --models "${provider}/${daily},${provider}/${reasoning}" --approve "$@"
}
function pi-xai() { _ai_require pi || return 1; _provider_env_or_die xai || return 1; local d="${XAI_MODEL_DAILY:-grok-4.3}" r="${XAI_MODEL_REASONING:-grok-4.6}"; _pi_provider xai-grok "${XAI_BASE_URL:-https://api.x.ai/v1}" '$XAI_API_KEY' "${XAI_DEFAULT_MODEL:-$d}" "$d" "$r" "$@"; }
function pi-azure() { _ai_require pi || return 1; _provider_env_or_die azure || return 1; local d="${AZURE_OPENAI_MODEL_DAILY:-gpt-5.4-mini-azure}" r="${AZURE_OPENAI_MODEL_REASONING:-gpt-5.4-azure}"; _pi_provider azure-foundry "$(_azure_base_url)" '$AZURE_OPENAI_API_KEY' "${AZURE_OPENAI_DEFAULT_MODEL:-$d}" "$d" "$r" "$@"; }

_cline_provider() { local base="$1" key="$2" model="$3"; shift 3; _ai_require cline || return 1; command cline auth -p openai -b "$base" -k "$key" -m "$model" || return 1; command cline --yolo -P openai -m "$model" -k "$key" "$@"; }
function clinex() { _ai_require cline || return 1; print.success "Starting Cline with full permissions (--yolo)..."; command cline --yolo "$@"; }
function cline-xai() { _provider_env_or_die xai || return 1; _cline_provider "${XAI_BASE_URL:-https://api.x.ai/v1}" "$XAI_API_KEY" "${XAI_DEFAULT_MODEL:-${XAI_MODEL_DAILY:-grok-4.3}}" "$@"; }
function cline-azure() { _provider_env_or_die azure || return 1; _cline_provider "$(_azure_base_url)" "$AZURE_OPENAI_API_KEY" "${AZURE_OPENAI_DEFAULT_MODEL:-${AZURE_OPENAI_MODEL_DAILY:-gpt-5.4-mini-azure}}" "$@"; }
function clinex-azure() { cline-azure "$@"; }

function grokx() { _ai_require grok || return 1; _provider_env_or_die xai || return 1; print.success "Starting official Grok CLI (xAI)..."; case "${1:-}" in -c|--continue) shift; command grok --continue "$@";; -r|--resume) shift; command grok --resume "$@";; *) command grok "$@";; esac; }
# Cursor is RESOLVED, never assumed. The Grok installer also creates an `agent`
# symlink pointing at the Grok binary, so a bare `agent` launches Grok — silently,
# because both are coding agents and both start a session. Prefer `cursor-agent`,
# and accept `agent` only when it is not Grok.
_cursor_bin() {
    if command -v cursor-agent >/dev/null 2>&1; then printf 'cursor-agent'; return 0; fi
    if command -v agent >/dev/null 2>&1 && ! agent --version 2>/dev/null | grep -qi grok; then
        printf 'agent'; return 0
    fi
    return 1
}
function cursorx() {
    local bin
    bin="$(_cursor_bin)" || { print.error "the Cursor CLI is not installed (\`agent\` on PATH is Grok). Rebuild the container."; return 1; }
    case "${1:-}" in
        -c|--continue) shift; command "$bin" resume "$@" ;;
        -l|--list) shift; command "$bin" ls "$@" ;;
        -r|--resume) shift; command "$bin" resume "$@" ;;
        *) command "$bin" "$@" ;;
    esac
}
